# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestRefresh1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestRefresh1

  pod 'MJRefresh'

  target 'TestRefresh1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestRefresh1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
